### ISSUE TITLE
masterブランチを保護したい

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/linebot-workspace#3]
### やりたいこと
- masterブランチへのpush禁止
---
https://next.rikunabi.com/journal/20170516_t12_iq/

上記事を参考に、やってみた。
できてるのかな？

**Comment by tanacchi** [comment]
できてますできてます。
MYDRY でも実はやってました。

**Comment by rkdora** [comment]
https://github.com/kyutech-programming-club/linebot-workspace/commit/2ce51838f738e7b5739345a3d3d7695730e89a4f

masterからpushしたらできちゃった。。。
設定ミスってるっぽい？？？

**Comment by rkdora** [comment]
masterへの強制push→禁止
masterへの通常push→可能
