### ISSUE TITLE
[Node.js]===と==の違い

### ISSUE THREAD

**Issue by rkdora** [kyutech-programming-club/linebot-workspace#5]
参考
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

![image](https://user-images.githubusercontent.com/20394831/55531190-3f893680-56e4-11e9-9965-74efa0920aee.png)

上はわかる。

下の、「異なるオブジェクトを参照してる」というのが理解できてない。
![image](https://user-images.githubusercontent.com/20394831/55531331-d0f8a880-56e4-11e9-8cb9-0f00e52a5744.png)

**Comment by syu-kwsk** [comment]
aとbを宣言したときに確保したメモリの場所が違うからではないでしょうか？

**Comment by tanacchi** [comment]
> aとbを宣言したときに確保したメモリの場所が違うからではないでしょうか？

まさにそんな感じ。
ちなみに、
```js
let a = new String('foo');
let c = a;

console.log(a === c);  // true
```
上が成り立つのは
```js
let c = a;
```
が、C言語でいうポインタのコピーに近い動きをしているから

**Comment by tanacchi** [comment]
問題解決したっぽいので閉じます
